/* Automatically generated by configure - do not modify! */
#define VERSION "1.1a"
#define PACKAGE "ushare"
#define PACKAGE_NAME "uShare"
#define SYSCONFDIR "/home/wenjian_jia/trunk/users/dlna_dms/tmp/etc"
#define LOCALEDIR "/home/wenjian_jia/trunk/users/dlna_dms/tmp/share/locale"
