# Automatically generated by configure - do not modify!
VERSION=1.1a
PREFIX=/home/wenjian_jia/trunk/users/dlna_dms/tmp
prefix=$(DESTDIR)$(PREFIX)
bindir=$(DESTDIR)${PREFIX}/bin
sysconfdir=$(DESTDIR)${PREFIX}/etc
localedir=$(DESTDIR)${PREFIX}/share/locale
MAKE=make
CC=rsdk-linux-gcc
LN=ln
STRIP=echo ignoring strip
INSTALLSTRIP=
EXTRALIBS= -lixml -lthreadutil -lpthread -lupnp -L/home/wenjian_jia/trunk/users/dlna_dms/tmp/lib
OPTFLAGS=-I/home/wenjian_jia/trunk/target/tmpfs/include -I/home/wenjian_jia/trunk/target/tmpfs/include -W -Wall -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -g3 -DHAVE_DEBUG -O3 -DHAVE_LOCALE_H -DHAVE_SETLOCALE -DHAVE_LANGINFO_H -DHAVE_LANGINFO_CODESET -I/home/wenjian_jia/trunk/users/dlna_dms/tmp/lib -pthread -I/home/wenjian_jia/trunk/users/dlna_dms/tmp/include/upnp
LDFLAGS= -L/home/wenjian_jia/trunk/users/dlna_dms/tmp/lib
INSTALL=/usr/bin/install -c
DEBUG=yes
