#ifndef __UI_MENU_H__
#define __UI_MENU_H__

#define MENU_ID_VIEW				0
#define MENU_ID_CONFIG				1
#define MENU_ID_PHONEBOOK			2
#define MENU_ID_TEST_CASE			3

#define MENU_ID_VIEW_NET			0
#define MENU_ID_VIEW_PING			1
#define MENU_ID_VIEW_SOFT_VER		2
#define MENU_ID_VIEW_CALL_RECORDS	3

#define MENU_ID_VIEW_NET_IP			0
#define MENU_ID_VIEW_NET_NETMASK	1
#define MENU_ID_VIEW_NET_GATEWAY	2
#define MENU_ID_VIEW_NET_DNS		3

#define VIEW_NET_IP_ID_LAN			0
#define VIEW_NET_IP_ID_WAN			1
#define NUM_OF_VIEW_NET_IP			2

#define CONFIG_ID_KEYPRESS_TONE			0
#define CONFIG_ID_OUTVOL_RECEIVER		1
#define CONFIG_ID_OUTVOL_SPEAKER		2
#define CONFIG_ID_INVOL_MIC_R			3
#define CONFIG_ID_INVOL_MIC_S			4
#define CONFIG_ID_AUTO_DIAL_TIME		5
#define CONFIG_ID_AUTO_ANSWER_TIME		6
#define CONFIG_ID_OFF_HOOK_ALARM_TIME	7
#define CONFIG_ID_HOT_LINE				8
#define NUM_OF_CONFIG					9

#define VIEW_CALL_RECORD_ID_MISSED		0
#define VIEW_CALL_RECORD_ID_INCOMING	1
#define VIEW_CALL_RECORD_ID_OUTGOING	2

#define TEST_CASE_ID_TEXT_ANI_VERTICAL		0
#define TEST_CASE_ID_TEXT_ANI_HORIZONTAL	1
#define TEST_CASE_ID_TEXT_CHINESE			2


#endif /* __UI_MENU_H__ */

