#ifndef __UI_STATE_H__
#define __UI_STATE_H__

typedef void ( *pFnSetupFrame_t )( int );
typedef void ( *pFnOnKey_t )( unsigned char );

typedef enum {
	STATE_TIMER_IDX_SLEEP = 0,	/* 30 seconds */
	STATE_TIMER_IDX_STANDBY,	/* 5 seconds */
	STATE_TIMER_IDX_STANDBY_T,	/* 1 seconds */
	STATE_TIMER_IDX_CURSOR,		/* 0.1 second */
	STATE_TIMER_IDX_MENU,		/* 0.5 seconds */
	STATE_TIMER_IDX_PROMPT,		/* 0.1 second */
	STATE_TIMER_IDX_CONFIRM,	/* 0.5 second */
	STATE_TIMER_IDX_CALL,		/* 1 second */
	NUM_OF_STATE_TIMER_IDX,
} idxStateTimer_t;

typedef enum {
	CANCEL_KEY_ACT_DEPENDS,
	CANCEL_KEY_ACT_BACK_ONE_LEVEL,
	CANCEL_KEY_ACT_STANDBY,
	NUM_OF_CANCEL_KEY_ACT,
} idCancelKeyAct_t;

typedef struct ui_state_context_s {
	pFnSetupFrame_t		pFnSetupFrame;
	pFnOnKey_t			pFnOnKey;
	idxStateTimer_t		nStateTimerIdx;
	idCancelKeyAct_t	nCancelKeyAct;
	int					nCancelKeyBackParam;
} ui_state_context_t;

typedef enum {
	UI_STATE_INIT,
	UI_STATE_STANDBY,	/* In normal operation */
	
	UI_STATE_DIAL,
	UI_STATE_DIAL_TIMEOUT,

	UI_STATE_INCOMING_CALL,
	UI_STATE_INCOMING_CALL_WAIT,
	UI_STATE_OUTGOING_CALL,
	UI_STATE_IN_CONNECTION,
	UI_STATE_IN_CONN_DIAL,
	UI_STATE_DISCONNECTION_WAIT,
	UI_STATE_DISCONNECTION,	
	
	UI_STATE_MENU_ACT,
	UI_STATE_MENU_VIEW,
	UI_STATE_MENU_VIEW_NET,
	UI_STATE_MENU_VIEW_NET_IP,
	UI_STATE_MENU_VIEW_NET_NETMASK,
	UI_STATE_MENU_VIEW_NET_GATEWAY,
	UI_STATE_MENU_VIEW_NET_DNS,
	UI_STATE_MENU_VIEW_SOFT_VER,
	UI_STATE_MENU_VIEW_PING,
	UI_STATE_MENU_VIEW_PING_WAIT,
	UI_STATE_MENU_VIEW_CALL_RECORDS,


	UI_STATE_MENU_CONF,
	UI_STATE_MENU_CONF_OUTVOL_RECEIVER,
	UI_STATE_MENU_CONF_OUTVOL_SPEAKER,
	UI_STATE_MENU_CONF_INVOL_MIC_R,
	UI_STATE_MENU_CONF_INVOL_MIC_S,
	UI_STATE_MENU_CONF_AUTO_DIAL_TIME,
	UI_STATE_MENU_CONF_AUTO_ANSWER_TIME,
	UI_STATE_MENU_CONF_OFF_HOOK_ALARM_TIME,
	UI_STATE_MENU_CONF_HOT_LINE,

	UI_STATE_MENU_TEST_CASE,
	UI_STATE_MENU_TEST_CASE_TEXT_VERTICAL,
	UI_STATE_MENU_TEST_CASE_TEXT_HORIZONTAL,
	UI_STATE_MENU_TEST_CASE_TEXT_CHINESE,

	UI_STATE_CALL_RECORD_MISSED,
	UI_STATE_CALL_RECORD_INCOMING,
	UI_STATE_CALL_RECORD_OUTGOING,
	UI_STATE_CALL_RECORD_MISSED_DETAIL,
	UI_STATE_CALL_RECORD_INCOMING_DETAIL,
	UI_STATE_CALL_RECORD_OUTGOING_DETAIL,

	UI_STATE_PHONEBOOK_LIST,
	UI_STATE_PHONEBOOK_EDIT_NAME,
	UI_STATE_PHONEBOOK_EDIT_NUMBER,
	UI_STATE_PHONEBOOK_ACT,
	UI_STATE_PHONEBOOK_ACT_ADD,
	UI_STATE_PHONEBOOK_ACT_MODIFY,
	UI_STATE_PHONEBOOK_ACT_DEL,
	UI_STATE_PHONEBOOK_ACT_DEL_ALL,
	UI_STATE_PHONEBOOK_ACT_STATUS,
	
	UI_STATE_PROMPT,
	NUM_OF_UI_STATE,	/* keep it to be last one */
} ui_state_t;

#endif /* __UI_STATE_H__ */

