#!/bin/sh

ifconfig lo 127.0.0.1

USE_SAMBA=0
CINIT=1

hostname rlx-linux

mount -t proc proc /proc
mount -t ramfs ramfs /var

#insert module init here by sed

mkdir /var/tmp
mkdir /var/web
mkdir /var/log
mkdir /var/run
mkdir /var/lock
mkdir /var/system
mkdir /var/dnrd
mkdir /var/lib
mkdir /var/lib/misc

##For miniigd
#mkdir /var/linuxigd
#cp /etc/tmp/pics* /var/linuxigd 2>/dev/null

##For pptp
#mkdir /var/ppp
#mkdir /var/ppp/peers

#smbd
#mkdir /var/config
#mkdir /var/private
#mkdir /var/tmp/usb

#cp /bin/pppoe.sh /var/ppp/true
#echo "#!/bin/sh" > /var/ppp/true
#echo "PASS"     >> /var/ppp/true

#extact web pages
cd /web
flash extr /web
cd /

mkdir -p /var/udhcpc
#mkdir -p /var/udhcpd
cp /bin/init.sh /var/udhcpc/eth0.deconfig
echo " " > /var/udhcpc/eth0.deconfig
cp /bin/init.sh /var/udhcpc/eth1.deconfig
echo " " > /var/udhcpc/eth1.deconfig
cp /bin/init.sh /var/udhcpc/br0.deconfig
echo " " > /var/udhcpc/br0.deconfig
cp /bin/init.sh /var/udhcpc/wlan0.deconfig
echo " " > /var/udhcpc/wlan0.deconfig

if [ "$CINIT" = 1 ]; then
startup.sh
fi

flash default-fc

# for wapi certs related
mkdir /var/myca
# wapi cert(must done before init.sh)
cp -rf /usr/local/ssl/* /var/myca/ 2>/dev/null
# loadWapiFiles >/dev/null 2>&1
 
# for wireless client mode 802.1x
mkdir /var/1x
cp -rf /usr/1x/* /var/1x/ 2>/dev/null
 
# Start system script
init.sh ap all

# modify dst-cache setting
echo 2048 > /proc/sys/net/ipv4/route/max_size
echo 180 > /proc/sys/net/ipv4/route/gc_thresh
echo 1 > /proc/sys/net/ipv4/route/gc_elasticity
echo 35 > /proc/sys/net/ipv4/route/gc_interval
echo 60 > /proc/sys/net/ipv4/route/secret_interval
echo 10 > /proc/sys/net/ipv4/route/gc_timeout
 
#echo "4096" > /proc/sys/net/nf_conntrack_max
#echo "420" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_established
#echo "60" > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout
#echo "5" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_time_wait
#echo "5" > /proc/sys/net/ipv4/netfilter/ip_conntrack_tcp_timeout_close
#echo "90" > /proc/sys/net/ipv4/netfilter/ip_conntrack_udp_timeout_stream
#echo "90" > /proc/sys/net/ipv4/netfilter/ip_conntrack_generic_timeout
echo 1 > /proc/sys/net/ipv4/ip_forward
#echo 2048 > /proc/sys/net/core/hot_list_length

# start web server
webs&

#USE_SAMBA=1
if [ "$USE_SAMBA" = 1 ]; then 
	#samba
	echo "start samba"
	cp /etc/smb.conf /var/config/smb.conf
	echo " " > /var/group
	cp /etc/group /var/group
	#usb and samba
	echo /usr/hotplug > /proc/sys/kernel/hotplug
	mkdir -p /tmp/usb/
	/bin/smbd -D 
	DEVPATH=/sys/block/sda ACTION=add usbmount block
	DEVPATH=/sys/block/sda/sda1 ACTION=add usbmount block
fi
