#!/bin/sh

ifconfig lo 127.0.0.1

USE_SAMBA=0
CINIT=1

mount -t proc proc /proc
mount -t ramfs ramfs /var

mkdir /var/tmp
mkdir /var/log
mkdir /var/run
mkdir /var/lock
mkdir /var/system
mkdir /var/lib
mkdir /var/lib/misc

# Start system script
/bin/sh /bin/mp.sh
UDPserver &
