#!/bin/sh

case "${ACTION}" in
 add)
  usbmount $1
  ;;
  *)
   usbmount $1
   ;;
esac

PID_FILE=/var/run/usbStorageD_pid
if [ -e $PID_FILE ]; then
        PID=`cat $PID_FILE`
        kill -USR1 $PID
fi      
